-- AlterTable
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "paymeId" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "paymeState" INTEGER;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "paymeCreateTime" BIGINT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "paymePerformTime" BIGINT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "paymeCancelTime" BIGINT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "paymeReason" INTEGER;

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "Order_paymeId_key" ON "Order"("paymeId");
