/** O‘zbekiston yetkazib berish hamkorlari */
export const UZ_COURIERS = [
  {
    code: "BTS",
    name: "BTS Express",
    nameUz: "BTS Express",
    phone: "+998712000000",
    website: "https://bts.uz",
    apiBaseUrl: "https://api.bts.uz",
    supportsCod: true,
    notes: "Pochta, kuryer, fulfillment. Ombordan topshirish.",
    sortOrder: 1,
  },
  {
    code: "FARGO",
    name: "Fargo",
    nameUz: "Fargo",
    phone: "+998712050505",
    website: "https://fargo.uz",
    apiBaseUrl: "https://api.fargo.uz",
    supportsCod: true,
    notes: "E-commerce last-mile, pickup point va locker.",
    sortOrder: 2,
  },
  {
    code: "UZPOST",
    name: "UzPost",
    nameUz: "O‘zbekiston pochtasi",
    phone: "+998712330033",
    website: "https://uz.post",
    apiBaseUrl: "https://api.uz.post",
    supportsCod: true,
    notes: "Milliy pochta, viloyatlar bo‘ylab punktlar.",
    sortOrder: 3,
  },
  {
    code: "YANDEX",
    name: "Yandex Delivery",
    nameUz: "Yandex Yetkazib berish",
    phone: null,
    website: "https://delivery.yandex.com",
    apiBaseUrl: "https://b2b.taxi.yandex.net",
    supportsCod: true,
    notes: "Tezkor shahar ichi / intercity yetkazish.",
    sortOrder: 4,
  },
  {
    code: "EXPRESS24",
    name: "Express24",
    nameUz: "Express24",
    phone: null,
    website: "https://express24.uz",
    apiBaseUrl: null,
    supportsCod: true,
    notes: "Tezkor yetkazib berish xizmati.",
    sortOrder: 5,
  },
  {
    code: "EMUS",
    name: "Emus Express",
    nameUz: "Emus Express",
    phone: null,
    website: "https://emus.uz",
    apiBaseUrl: null,
    supportsCod: true,
    notes: "Mahalliy kuryer xizmati.",
    sortOrder: 6,
  },
  {
    code: "STARK",
    name: "Stark Express",
    nameUz: "Stark Express",
    phone: null,
    website: null,
    apiBaseUrl: null,
    supportsCod: true,
    notes: "Tezkor kuryer.",
    sortOrder: 7,
  },
  {
    code: "LOCAL",
    name: "Local Courier",
    nameUz: "Mahalliy kuryer",
    phone: null,
    website: null,
    apiBaseUrl: null,
    supportsCod: true,
    notes: "Ombor yaqinidagi shaxsiy/mahalliy kuryer.",
    sortOrder: 99,
  },
] as const;
